site_name: RoboticsBrno developers team
site_url: https://team.robotikabrno.cz
site_author: RoboticsBrno
site_description: >-
  RoboticsBrno developers team
  This is RoboticsBrno developers team


# Repository
repo_name: RoboticsBrno/Our-team
repo_url: https://github.com/RoboticsBrno/Our-team

# Copyright
copyright: Copyright © 2024 RoboticsBrno

theme:
  name: material
  language: cs
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RoboticsBrno
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/RobotikaBrno
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/robotarna.helceletka
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@robotikabrno-robotarnaasps2392
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/robotarna.helceletka
#    analytics:
#        provider: google
#        property: G-XXXXXXXXXX

use_directory_urls: True

plugins:
  - search
  - glightbox
  - open-in-new-tab
#  - i18n:
#      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
#      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
#      docs_structure: suffix
#      languages:
#        default:
#          name: Default (en)
#          build: true
#        cs:
#          name: Czech (cs)
#          build: true
#          site_name: RB0011 Pájecí výzva
      # nav_translations:
      #   fr:
      #     Topic1: Sujet1
      #     Topic2: Sujet2
  - git-revision-date-localized


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      url_download: True
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: 'README.md'
  - How to use it: 'how-to-use-it.md'